#+TITLE: 表格基础


* Org Mode 表格基础：Built-in Table Editor

对照官方手册的 Chaper 3: Tables。

** 本节定位

这一节开始进入 Org 的另一个核心能力：表格。表格在纯文本中提供了一种可编辑、可对对齐、可计算的二维结构。

这一节最优先学习的部分：

- 什么是 Org 表格
- Org 如何识别表格
- 为什么和普通文本表格不一样
- 应当掌握的基本编辑动作


本节对应官方文档：

- Chapter 3: Tables
- 3.1 Built-in Table Editor
- 3.2 Column Width and Alignment


-----

** 为什么 Org 要内建表格

在普通纯文本里，表格通常很难维护。

比如：

#+BEGIN_EXAMPLE
|Name|Age|
|Tom|18|
|Alice|20|
#+END_EXAMPLE

问题在于，一旦内容变长，就会遇到列错位、手动补齐空格、插入列和移动行很麻烦等问题。

Org 的做法是：保留纯文本形式，但是让 Emacs 在编辑时把它定做“结构化表格对象”处。并且每次在表格里按 TAB、RET或C-c C-c都会自动对齐。

所以 Org 表格的核心思想是：文件里仍然是纯文本，但是在 Org mode里，它被当作一个受规则控制的二维结构。

-----

** Org 如何识别表格

官方规则非常直接：

- 任何一行，只要第一个非空白字符是 ~|~，就会被视为表格的一部分
- 以 ~|-~ 开头的行会被视为水平分割线
- 第一条水平分割线之前的行会被视为表头


比如：

| Name  | Phone | Age |
|-------+-------+-----|
| Peter |  1234 |  14 |
| Anna  |  4321 |  25 |

这里表格只要满足Org的语法规则，Org就会接管它的编辑行为。


-----

** 最基础的建表方式

最典型的方式是直接输入：

#+BEGIN_EXAMPLE
|Name|Phone|Age|
|-
#+END_EXAMPLE


然后按 TAB，Org 就会自动对齐并补全分割线。接着，光标就会移动到下一行的第一个单元格中。如下所示：

| Name | Phone | Age |
|------+-------+-----|
| Tom  |  1890 |  19 |

-----

** Org 看来，表格中的基本对象是什么

*** field

field 就是单元格。当点击 TAB 时，Org 本质上时在“跳到下一个 field”，官方把 TAB 绑定为 org-table-next-field。

*** row

row 是一整行。


按 RET 时，Org 会重对齐表格并移动到下一行，必要时自动创建新行，官方把 RET绑定为 org-table-next-row。

*** column

column 是纵向的一列。

后面移动列、删除列、插入列时，Org 直接以column为单位处理。

所以现在对表格的理解应该是：

表格 = 行 x 列 组成的 field网格，这样的二维结构。

-----

** 表格中的核心交互

*** 对齐

~C-c C-c~：重新对齐当前表格。

这个命令会 ~re-align the table without moving point~。

*** 横向移动

- ~TAB~: 重新对齐并移动到下一个 field
- ~S-TAB~: 重新对齐并到上一个 field


在表格里，TAB表示的是“表格字段导航”。

*** 纵向移动

- ~RET~: 重新对齐并移动到下一行
- 到表格末尾时可自动创建新行


-----

** 行列编辑：Org 表格的强大之处

官方给表格专门定义了一整套行列操作命令。

*** 列操作

- ~M-LEFT~: 当前列左移
- ~M-RIGHT~: 当前列右移
- ~M-S-LEFT~: 删除当前列
- ~M-S-RIGHT~: 在当前位置插入新列


*** 行操作

- ~M-UP~: 当前行上移
- ~M-DOWN~: 当前行下移
- ~M-S-UP~: 删除当前行
- ~M-S-DOWN~: 插入新行


在 Org 表格里，列是第一类结构对象，所以可以直接被移动。

-----

** 这一节必须掌握的内容

*** 能力A：会从零开始敲一个 Org 表格

*** 能力B：知道表格里的 TAB 和 RET 已经转换了语义

*** 会编辑行和列

*** 知道 Org 表格是二维结构对象

-----

** 本节总结

这一节需要掌握的：

第一，Org 表格是纯文本文件中的二维结构对象，它拥有内建表格编辑器，并会在 TAB、RET、C-c C-c时自动重新对齐。

第二，表格里，field、row、column都是第一类编辑对象。

第三，表格属于 Org 基础内容的组织能力，和 headline管理层级、list管理局部枚举一样，负责表达二维关系。


