:PROPERTIES:
:END:
#+title: 从 JavaSript 运行模型到 TypeScript 基础语法
#+date:       [2026-06-05 Fri 15:29]
#+identifier: 20260605T152908
* 总览
这一章的目标是让我能够独立写出一个小型 TypeScript 程序，并理解其中每一行代码在运行时和检查时分别发生了什么。

TypeScript 语法表面上更接近 Java ，但它的运行时模型与 Java 有明显差异：TypeScript 的目标是为 JavaSript 程序提供静态类型检查。代码实际运行时，执行的是编译后生成的 JavaSript 。Typescript 官方文档特别强调，类型标注不会改变程序的运行行为；大多数 TypeScript 专属语法会在编译期被移除。

本章结束时，我们会得到一个可运行小程序，并掌握：
- TypeScript 、 JavaScript 、 Node.js 和 pnpm 分别负责什么
- 如何声明变量，如何阅读类型标注
- 常用基本类型、数组、元组和对象
- 函数的定义、参数与返回值
- ~if~, ~for~ 等基本控制流程
- 类型推导的基本工作方式
- 如何有意识地制造类型错误，并利用编译器理解错误。

-----
* TypeScript 程序如何运行

一个模型：

#+begin_example
你编写的 index.ts
        │
        ▼
TypeScript 编译器 tsc
  ├─ 检查类型错误
  └─ 移除类型标注
        │
        ▼
生成 dist/index.js
        │
        ▼
Node.js 执行 JavaScript
#+end_example

其中，

- ~.ts~ 是 TypeScript 源文件
- ~.js~ 是 JavaScript 文件
- ~tsc~ 是 TypeScript 编译器
- ~Node.js~ 是 JavaScript 运行时
- ~pnpm~ 用于管理依赖和执行项目脚本


例如，下面是 TypeScript:

#+begin_src typescript-ts
  const name: string = "Alice";
  const score: number = 92;

  console.log(`${name}: ${score}`);
#+end_src

编译后会大致得到：

#+begin_src javascript
  const name = "Alice";
  const score = 92;

  console.log(`${name}: ${score}`);
#+end_src

这里的 ~:string~ 和 ~:number~ 消失了。它们用于编译时检查。

-----
* 创建本章项目

具体参照 [[file:~/Learning/projects/typescript-learn/][本章项目参照]]。
-----
* 第一个 TypeScript 程序

创建 ~src/index.ts~ :

#+begin_src typescript-ts
  const courseName: string = "TypeScript 入门";
  const completedLessons: number = 0;
  const isFinished: boolean = false;

  console.log(`课程: ${courseName}`);
  console.log(`已完成课时： ${completedLessons}`);
  console.log(`是否完成: ${isFinished}`);
#+end_src

执行:

#+begin_src bash
  pnpm build
  pnpm start
#+end_src

这里展示了三种最基础的类型，可以按照下面的结构阅读：

~const 变量名: 类型 = 值~ 。

例如：

#+begin_src typescript-ts
  const age: number = 22;
#+end_src

表示创建一个名为 ~age~ 的常量，它保存一个数字，初始值是 ~22~ 。

-----
* ~const~, ~let~ 与变量

TypeScript 继承了 JavaScript 的变量声明方式。日常开发中，优先使用 ~const~ ；需要重新赋值时使用 ~let~ 。TypeScript 官方文档也将 ~let~ 和 ~const~ 视为比 ~var~ 更适合现代代码的声明方式。
** ~const~: 变量不能重新绑定

比如：
#+begin_src typescript-ts
  const language: string = "TypeScript";
#+end_src

下面的代码会报错： ~language = "OCaml";~ 。因为使用 ~const~ 声明后，变量不能指向另一个值。
** ~let~ 允许重新赋值

#+begin_src typescript-ts
  let score: number = 60;

  score = 75;
  score = 92;
#+end_src

而这段代码仍然会报错: ~score = "优秀"~ ，因为 ~score~ 虽然可以改变，但是其只能保存 ~number~ 。
** 一个使用习惯
先默认使用 ~const~ ，发现确实需要修改时候，再改成 ~let~ 。

这样可以减少无意间修改变量的机会。

-----
* 类型推导

很多地方都无需手动标注。比如，下面两种写法都合法：

#+begin_src typescript-ts
  const username: string = "Alice"
  const username2 = "Bob"
#+end_src

第二行没有写类型标注 ~:string~ ，但 TypeScript 仍能推断 ~username2~ 是字符串。

因此，日常编码中可以采用一个简单原则：

当类型能够清晰推导时，保留推导结果即可。对于函数参数等缺乏上下文的位置，通常需要手动标注类型。

#+begin_src typescript-ts
  function greet(name: string): string {
    return `Hello, ${name}`;
  }
#+end_src


TypeScript 官方文档将类型推导列为核心使用方法之一。

-----
* 常用基本类型
** ~string~
字符串常用于表示文本。

推荐掌握模板字符串，使用反引号：

#+begin_src typescript-ts
  `文本 ${表达式}`
#+end_src

~${...}~ 中可以放入表达式：

#+begin_src typescript-ts
  const x = 3;
  const y = 4;
  console.log(`${x} + ${y} = ${x + y}`);
#+end_src

输出: ~3 + 4 = 7~ 。
** ~number~

JavaScript 和 TypeScript 日常使用统一的 ~number~ 类型：

#+begin_src typescript-ts
  const age: number = 22;
  const price: number = 19.9;
  const temperatur: number = -8;
#+end_src

没有 Java 中常见的 ~int~ , ~long~ , ~float~ 和 ~double~ 等区分。
** ~boolean~
布尔值只有两个： ~true~ 和 ~false~ 。

比较表达式会得到布尔值：

#+begin_src typescript-ts
  cosnt score = 72;
  cosnt passed = score >= 60;
  console.log(passed); // true
#+end_src

常用比较运算符：

#+begin_src typescript-ts
  a === b
  a !== b
  a > b
  a >= b
  a < b
  a <= b
#+end_src

优先使用严格相等： ~a === b~ ，避免旧式的宽松比较： ~a == b~ 。

JavaScript 的宽松比较会进行隐式类型转换，容易产生反直觉结果。
** ~null~ 与 ~undefined~

它们都用于表示“当前没有值”，含义有所区别。
*** 基本区别
~undefined~ 通常表示：这个值还没有被提供、没有被赋值、或者不存在。

#+begin_src typescript-ts
  let name: string | undefined = undefined;
  console.log(name); // undefined
#+end_src

变量声明后没有赋值，默认就是 ~undefined~ 。

~null~ 通常表示：程序明确地把这个位置设置为空。

#+begin_src typescript-ts
  let selectedUser: string | null = null;
#+end_src

这里的含义更接近：“目前没有明确选中的用户”。

可以把两者理解成：

| 值          | 常见语义                   |
|-------------+----------------------------|
| ~undefined~ | 没有提供、尚未赋值、找不到 |
| ~null~      | 明确设置为空、明确不存在   |
*** 常见来源

未初始化变量会得到 ~undefined~
#+begin_src typescript-ts
  let count: number | undefined
  console.log(count); // undefined
#+end_src

对象中不存在的属性会得到 ~undefined~

#+begin_src typescript-ts
  const user = {
    name: "Alice";
  };
  console.log(user.age); // undefined
#+end_src

不过在 TypeSript 中，直接访问不存在的属性通常会报类型错误。

如果属性本身是可选的，就可能得到 ~undefined~:

#+begin_src typescript-ts
  type User = {
    name: string
    age?: number
  };

  const user: User = {
    name: "Alice"
  };

  console.log(user.age); // undefined
#+end_src

这里的 ~age?: number~ 可以近似理解为 ~age: number | undefined~ 。


函数参数没有传入时，会得到 ~undefined~:

#+begin_src typescript-ts
  functoin greet(name?: string) {
    console.log(name);
  }

  greet(); // undefined
#+end_src

数据越界访问会得到 ~undefined~:

#+begin_src typescript-ts
  const numbers = [10, 20]
  console.log(numbers[10]); // undefined
#+end_src

注意，TypeScript 未必会提示数组越界风险，之后可以通过 ~noUncheckedIndexedAccess~ 来增强检查。

~null~ 通常由程序主动写入:

#+begin_src typescript-ts
  let currentuser: User | null = null;
#+end_src

这通常代表着程序设计中的一个 *明确状态*， 例如 “用户尚未登录”。
*** 它们是两个不同的值

严格相等 ~===~ 会认为它们不同。但使用宽松相等 ~==~ 的时候，会认为它们是相等的。
*** ~strictNullChecks~
这是 ~tsconfig.json~ 中的配置，当启用了 ~compilerOptions.strict: true~ 时，其中就包含 ~strictNullChecks~ 。开启后， ~null~ 和 ~undefined~ 都不能随意赋值给其他类型。

必须要显式声明:

#+begin_src typescript-ts
  let username: string | null = null;
#+end_src
 或者同时声明两者:

 #+begin_src typescript-ts
   let username: string | null | undefined
 #+end_src

 这样的约束可以提前发现运行时错误，比如：

 #+begin_src typescript-ts
   function printLength(text: string | undefined) {
     console.log(text.lenght);
   }
 #+end_src

 TS 会报错，因为 ~text~ 可能是 ~undefined~ 。我们需要先检查:

 #+begin_src typescript-ts
   function printLength(text: string | undefined) {
     if (text !== undefined) {
       console.log(text.length);
     }
   }
 #+end_src
*** 可选参数通常用 ~undefined~

函数参数没有传入时， JavaScript 会自动使用 ~undefined~:

#+begin_src typescript-ts
  function greet(name?: string) {
    if (name === undefined) {
      console.log("没有提供名字");
      return;
    }
    console.log(`你好，${name}`);
  }

  greet();
  greet("Alice");
#+end_src

因此可选参数一般写成 ~name?: string~ 或者 ~name: string | undefined~ 。

但是二者有细微区别。比如我们定义两个函数:

#+begin_src typescript-ts
  function f1(name?: string) {}
  function f2(name: string | undefined) {}

  f1(); // 可以不传参数
  f2(); // 报错：必须传入一个参数
  f2(undefined); // 可以
#+end_src

- ~name?: string~ 表示参数本身可以省略
- ~name:string | undefined~ 表示参数位置仍然存在，但值可以是 ~undefined~ 。
*** 对象属性中的区别
对象属性也有类似差别：

#+begin_src typescript-ts
  type UserA = {
    nickname?: string;
  };

  const userA: UserA = {};
#+end_src
表示 ~nickname~ 属性可以不存在。

而:

#+begin_src typescript-ts
  type UserB = {
    nickname: string | undefined;
  };

  const userB: UserB = {
    nickname: undefined;
  };
  const userB: UserB = {}; // 报错，缺少 nickname 属性
#+end_src

表示属性必须存在，只是值可以为 ~undefined~ 。而第二个 ~const~ 声明则会报错。

这个区别在接口设计中很有用。
*** JSON 中的表现不同
~undefined~ 和 ~null~ 还有一个十分实际的区别。

#+begin_src typescript-ts
  const data = {
    a: undefined,
    b: null,
  };

  console.log(JSON.stringify(data));
#+end_src

结果是： ~{"b":null}~ 。对象中的 ~undefined~ 的属性会被省略， ~null~ 则会被保留下来。

这会影响前后端接口。比如:

#+begin_src typescript-ts
  {
    nickname: undefined
  }
#+end_src
序列化后可能代表“不要更新昵称”。

而

#+begin_src typescript-ts
  {
    nickname: undefined
  }
#+end_src

序列化后可能代表“把昵称清空”。
*** 空值合并运算符 ~??~
当值可能是 ~null~ 或 ~underfined~ 时，可以使用 ~??~ 提供默认值。

比如:

#+begin_src typescript-ts
  const username: string | null = null;
  console.log(username ?? "匿名用户");
#+end_src
~??~ 只处理 ~null~ 和 ~undefined~ ，不会把 ~0~ ， ~false~ 或空字符串视为空值。

比如接下来的:

#+begin_src typescript-ts
  console.log(0 ?? 100);
  console.log(false ?? true);
  console.log("" ?? "default");
#+end_src

在严格的类型检查下，上面三种写法会报错:

#+begin_quote
error TS2869: Right operand of ?? is unreachable because the left operand is never nullish.
#+end_quote

而比如 ~||~:

#+begin_src typescript-ts
  console.log(0 || 100); // 100
  console.log(false || true); // true
  console.log("" || "default"); // default
#+end_src

多数涉及缺省值的场合， ~??~ 更准确。
*** 可选链 ~?.~
当对象可能是 ~null~ 或 ~undefined~ 时，可以使用可选链:

#+begin_src typescript-ts
  type User = {
    profile?: {
      nickname?: string;
    };
  };
  const user: User = {};

  console.log(user.profile?.nickname); // undefined
#+end_src

如果 ~profile~ 不存在，会直接返回 ~undefined~ , 不会报错。

还可以搭配 ~??~:

#+begin_src typescript-ts
  const nickname = user.profile?.nickname ?? "default";
#+end_src
*** 实际开发中如何选择 ~undefined~ 和 ~null~

一般采用这样的习惯:

- 函数可选参数、对象选择属性、查找失败结果，优先使用 ~undefined~ 。
- 需要明确表达 "为空" 的业务状态时，使用 ~null~ 。例如:
  #+begin_src typescript-ts
    type Session = {
      currentUser: User | null;
    };

    const session: Session = {
      currentUser: null;
    };
  #+end_src
  这里的 ~null~ 表示系统明确知道：当前没有登陆用户。
- 如果没有特殊需要，避免让同一个字段同时拥有 ~null~ 和 ~undefined~:
  #+begin_src typescript-ts
    let user: User | null | undefined; 
  #+end_src

  这种类型会增加判断成本，最好根据业务语义选择其中一种。
*** 一个完整示例：

#+begin_src typescript-ts
  function findUsers(id: number): User | undefined {
    const users: User[] = [
      { id: 1, nickname: "Alice" },
      { id: 2},
    ];
    return users.find((user) => user.id === id);
  }

  const user = findUsers(2);
  const nickname = user?.nickname ?? "Default";
  console.log(nickname);
#+end_src

这里有两种不同的 ~undefined~ 来源：

~findUser(2)~ 找到了用户，因此返回的是 ~User~ 。但是由于该用户 ~user.nickname~ 没有，因此后面使用 ~user?.nickname ?? "Default"~ 进行兜底。

-----
* 数组
数组用于保存一组元素:

#+begin_src typescript-ts
  const scores: number[] = [92, 48, 76];
  const names: string[] = ["Alice", "Bob", "Carol"];
#+end_src

~number[]~ 表示数字数组， ~string[]~ 表示字符串数组。

常用操作:

#+begin_src typescript-ts
  const languages string[] = ["TypeScript", "Java", "OCaml"];
  console.log(languages[0]);
  console.log(languages.length);
  languages.push("C++");
  console.log(languages);
#+end_src
注意这里使用 ~push~ ，虽然数组声明时用的是 ~const~ ，但是数组内部仍然可以变化。 ~const~ 限制的是变量重新绑定，比如 ~languages = ["C++"]~ ，这在类型检查前，语法层面就不允许重新赋值。而对于数组内部，只要绑定不变则可以变更。

如果希望数组内部也尽可能只读，则可以使用:

#+begin_src typescript-ts
  const languages: readonly string[] = ["TypeScript", "Java"];
#+end_src

此时就不能 ~push~ 了。

-----
* 元组：长度和每个位置都有约束的数组
数组通常只约束元素类型：

#+begin_src typescript-ts
  const score: number[] = [98, 80, 76];
#+end_src
元组还约束元素数量和位置:

#+begin_src typescript-ts
  const user: [string, number] = ["Alice", 22];
#+end_src

含义是：
- 第0的位置必须是 ~string~
- 第1个位置必须是 ~number~


下面的写法会报错: ~const user: [string, number] = [22, "Alice"];~

元组适合表达结构固定的小型数据，比如:

#+begin_src typescript-ts
  const coordinate: [number, number] = [10, 20];
  const httpResult: [number, string] = [200, "OK"];
#+end_src
不过，当数据含义较复杂时，对象通常更加清晰。
-----
* 对象
JavaScript 中，对象是极其常用的数据组织方式。它由若干属性组成：

#+begin_src typescript-ts
  const student = {
    name: "Alice",
    score: 92,
    passed: true
  };
#+end_src
读取属性则使用 ~student.name~ 。修改属性也可以通过 ~student.score = 95~ 进行直接修改。

也可以显式写出对象类型:

#+begin_src typescript-ts
  const student: {
    name: string;
    score: number;
    passed: boolean;
  } = {
    name: "Alice",
    score: 92,
    passed: true
  };
#+end_src

这里需要注意的是， *对象类型内部使用分号* ， *对象值内部使用逗号* 。

为了复用对象类型，可以定义 *类型别名* 。

#+begin_src typescript-ts
  type Student = {
    name: string;
    score: number;
    passed: boolean;
  };

  const alice: Student = {
    name: "Alice",
    socre: 92,
    passed: true
  };

  const bob: Student = {
    name: "Bob",
    score: 48,
    passed: false
  };
#+end_src

需要注意的是， ~type Student = ...~ 不会在运行时创建一个 Java 风格的类。它仅仅给某种数据形状起名字。

这体现了 TypeScript 的重要特点：很多时候我们关系一个对象“有哪些属性、属性分别是什么类型”，而暂时不关心它由哪个类创建。对象类型是 TypeScript 类型系统的核心组成部分。

-----
* 函数
函数接收输入、执行一些逻辑，并返回输出。
** 最基本的函数
#+begin_src typescript-ts
  function add(a: number, b: number): number {
    return a + b;
  }
#+end_src

调用函数:

#+begin_src typescript-ts
  const result = add(3, 4)
  console.log(result);
#+end_src
** 返回字符串
#+begin_src typescript-ts
  function formatScore(name: string, score: number): string {
    return `${name}: ${score}`;
  }
#+end_src
** 没有返回值: ~void~
#+begin_src typescript-ts
  function printMessage(message: string): void {
    console.log(message);
  }
#+end_src
~void~ 表示调用者不应该期待得到一个有用的返回值。
** 箭头函数
#+begin_src typescript-ts
  const multiply = (a: number, b: number): number => a * b;
#+end_src
箭头函数在数组处理、回调函数和闭包中会频繁出现。后续章节会专门讲解。

-----
* 条件分支与循环
** ~if~ 分支
#+begin_src typescript-ts
  function getLevel(score: number): string {
    if (score >= 90) {
      return "优秀";
    } else if (score >= 60) {
      return "及格";
    } else {
      return "不及格";
    }
  }

  console.log(getLevel(92));
#+end_src
** ~for ... of~ 循环
#+begin_src typescript-ts
  const scores: number[] = [92, 48, 76];

  for (const score of scores) {
    console.log(score);
  }
#+end_src
** 循环访问对象数组
#+begin_src typescript-ts
  type Student = {
    name: string;
    score: number;
  };

  const students: Student[] = [
    { name: "Alice", score: 92 },
    { name: "Bob", score: 48 },
    { name: "Carol", score: 76 }
  ];

  for (student of students) {
    console.log(`${student.name}: ${student.score}`);
  }
#+end_src
~Student[]~ 表示一个对象数组，其中每个元素都必须满足 ~Student~ 的结构要求。
-----
* 学生成绩统计程序

#+begin_src typescript-ts
  type Student = {
    name: string;
    score: number;
  };

  function hasPassed(score: number): boolean {
    return score >= 60;
  }

  function getLevel(score: number): string {
    if (score >= 90) {
      return "优秀";
    } else if (score >= 60) {
      return "及格";
    } else {
      return "不及格";
    }
  }

  function calculateAverage(students: Student[]): number {
    let total = 0;
    for (const student of students) {
      total += student.score;
    }
    return total / students.length;
  }

  const students: Student[] = [
    { name: "Alice", score: 92},
    { name: "Bob", score: 48 },
    { name: "Carol", score: 76 }
  ];

  for (const student of students){
    console.log(
      `${student.name}: ${student.score} 分, ${getLevel(student.score)}, ` +
        `是否通过: ${hasPassed(student.score)}`
    );
  }

  console.log(`平均分: ${calculateAverage(students)}`);
#+end_src
------
* 本章小结
这一章完成了 TypeScript 入门所需的第一层基础。我们首先区分了 TypeScript, JavaScrpt, Node.js, pnpm 与 tsc 的职责： TypeScript 负责在开发阶段检查类型， ~tsc~ 将 ~.ts~ 文件转化为 JavaScript, Node.js 负责执行生成的 JavaScript, 而 pnpm 用于管理依赖和项目脚本。 TypeScript 的类型信息主要服务于开发阶段，程序真正运行时，大多数类型标记都已经被移除。

在语法层面，我们学习了 ~const~ 与 ~let~ 、字符串、数字、布尔值、数组、元组和对象，并用 ~type~ 为对象结构命名。我们也掌握了函数参数与返回值的类型标注，以及 ~if~ 分支、 ~for ... of~ 循环等基础控制流程。

这一章还需要形成一个重要习惯：优先让 TypeScript 自动推导简单变量的类型，在函数参数、返回值和复杂数据结构上互动补充类型信息。类型标注并非越多越好，关键让程序的输入、输出和数据结构足够清晰。

下一章将在此基础上继续学习联合类型、字面量类型、可选属性、 ~any~, ~unknown~, ~void~ 与 ~never~ ，并进一步理解 TypeScript 如何根据程序分支逐步判断一个值的具体类型。
