#+title:      C++ 可执行程序形成过程（二）
#+date:       [2026-05-30 Sat 00:47]
#+filetags:   
#+identifier: 20260530T004716

#!TITLE: 从源码到可执行文件理解 Matrix 模块
* 本节定位

本节承接阶段0的项目准备，正式进入阶段1：C++ 模型基础

当前项目已经具备以下文件：

- ~cpp/main.cpp~
- ~cpp/Matrix.h~
- ~cpp/Matrix.cpp~
- ~CMakeLists.txt~


今天要解决的问题：

- [ ] ~main.cpp~ 为什么能使用 ~Matrix~?
- [ ] ~Matrix.h~ , ~Matrix.cpp~, ~CMakeLists.txt~ 分别在编译和链接中承担什么角色？
* 官方文档对应的内容：

- CMake add_executable：创建由指定源文件构建出的可执行目标。
- CMake target_include_directories：为某个 target 添加头文件搜索路径，并控制该路径的作用范围。
- cppreference translation phases：C++ 源文件会经历预处理、编译等翻译阶段，#include 会在预处理相关阶段处理。
- cppreference source file inclusion：被 include 的文件会继续经历翻译阶段中的前若干处理过程。
* 当前项目文件分工
** ~main.cpp~

~main.cpp~ 是程序入口，里面有 ~int main()~ 函数。

它负责创建 ~Matrix~ 对象，并调用 ~Matrix~ 提供的接口。

其中的关键是：
#+begin_src cpp
  #include "Matrix.h"
#+end_src

这一行会让 ~main.cpp~ 在编译时看见 ~Matrix~ 类的声明。
** ~Matrix.h~

这是接口文件，主要告诉其他源文件：

- 有一个类叫 ~Matrix~
- 它有哪些构造函数
- 它有哪些成员函数
- 外部代码可以怎样使用它


里面主要放声明，让其他源文件知道这个类的接口。
** ~Matrix.cpp~

这是实现文件，负责写出 Matrix 行为。
** ~CMakelists.txt~
编译文件。具体可参照上一节。
* 构建流程
在 ~main.cpp~ 中，会这样写：
#+begin_src cpp
  #include "Matrix.h"
  #include <iostream>

  int main() {
    Matrix wafer(3, 4, 0.0);

    wafer.at(0, 0) = 1.5;
    wafer.at(1, 2) = 9.8;
  }
#+end_src

表面上看， ~main.cpp~ 直接使用 ~Matrix~ 类。但是从 C++ 工程角度看， ~main.cpp~ 并没有 “读取” ~Matrix.cpp~ 。它只是包含了 ~Matrix.h~ 。

这就引出第一条关键结论：

~main.cpp~ 编译时，只需要知道 ~Matrix~ 的接口；真正的函数实现，可以在另一个 ~.cpp~ 文件中，最后通过链接阶段合并进来。

这里的 “接口” 就是 ~Matrix.h~ 中的内容。

#+begin_src cpp
  class Matrix {
  public:
    Matrix(std::size_t rows, std::size_t cols, double initial_value = 0.0);
    std::size_t rows() const;
    std::size_t cols() const;

    double& at(std::size_t row, std::size_t col);
    double at(std::size_t row, std::size_t col) const;
  }
#+end_src

这些语句告诉编译器：
- 有一个类型叫做 ~Matrix~
- 它可以用三个参数构造
- 它有 ~rows()~ , ~cols()~, ~at()~ 这些成员函数
- 其中一个 ~at()~ 返回 ~double&~ ，所以可以出现在赋值号左边：
  ~wafer.at(1, 2) = 9.8;~


到这里为止，编译器只是在检查“这段代码是否合法”。它还不需要知道 ~Matrix::at~ 内部到底要怎么访问 ~data_~ 。


-----

接下来讲构建流程

一个 C++ 程序从源码到可执行文件，大致可以理解为：

\[.cpp 源文件 \rightarrow 预处理 \rightarrow 编译 \rightarrow 汇编 \rightarrow 目标文件 .o \rightarrow 链接 \rightarrow 可执行文件 \]

[[https://zh.cppreference.com/cpp/language/translation_phases][cppreference 翻译阶段]] 中提到，C++ 源文件会被处理为 翻译单元(translation unit)，多个翻译单元可以分别翻译，之后链接生成可执行程序。

这里提到了 [[https://zh.cppreference.com/cpp/language/translation_phases#%E7%BF%BB%E8%AF%91%E9%98%B6%E6%AE%B5][九个翻译阶段]]，我们暂且不用纠结，可以按照工程实践理解。
** 预处理阶段

*预处理阶段* 主要处理 ~#include~ ，宏，条件编译。

比如： ~#include "Matrix.h"~ 可以粗略理解为：在编译 ~main.cpp~ 前，预处理器把 ~Matrix.h~ 里的内容展开进来。

