#+title: Paramter Pack
#+date:       [2026-07-15 Wed 17:38]
#+identifier: 20260715T173845
#+author: yurikon
#+language: zh-cn
* 参数包是什么
参数包是在编译期表示“零个或多个参数”的模板实体。

它解决的问题是：普通模板参数数量固定，而泛型代码经常需要接受任意数量、任意类型的参数。

普通模板:
#+begin_src cpp
  template <typename T>
  void process(T value);
#+end_src
只能描述一个类型参数。

可变参数模板:
#+begin_src cpp
  template <typename... Ts>
  void process(Ts... values);
#+end_src
其中 ~Ts~ 表示一组类型，而 ~values~ 表示一组函数参数。

参数包可以为空，也可以包含一个、两个或任意多个元素。
* 
#+begin_src cpp
  template <typename F, typename... Args>
  decltype(auto) invoke_and_log(F&& func, Args&&... args) {
    std::cout << "invoking..." << '\n';
    return std::invoke(std::forward<F>(func), std::forward<Args>(args)...);
  }
#+end_src
这里有两个普通模板相关参数 ~F~ 和 ~func~, 以及两个参数包 ~Args~ 和 ~args~.
** ~typename... Args~
#+begin_src cpp
  template <typename F, typename... Args>
#+end_src
这里声明了一个 *模板类型参数包*: ~Args~, 它是零个或多个类型组成的编译期序列。

例如调用:
#+begin_src cpp
  invoke_and_log(func, 42, 3.14, name);
#+end_src
假设 ~name~ 是一个左值 ~std::string~, 那么 ~Args~ 大致会被推导为:
#+begin_src cpp
  Args = <int, double, std::string&>
#+end_src
这里声明时使用的是转发引用，因此左值会被推导为左值引用类型。
** ~Args&&... args~
这里声明的是一个函数参数包。可以理解为:
#+begin_quote
对于 ~Args~ 中的每个类型，都生成一个名字属于 ~args~ 参数包的函数参数。
#+end_quote

例如:
#+begin_src cpp
  invoke_and_log(func, 42, 3.14, name);
#+end_src

对应生成的函数参数类型近似于:
#+begin_src cpp
  int&& arg0;
  double&& arg1;
  std::string&& arg2;
#+end_src
也就是说 ~Args&&... args~ 概念上相当于把模式 ~Args&&~ 分别应用到 ~Args~ 中的每个类型。

经过引用折叠:
#+begin_src cpp
  int&&
  doutble&&
  std::string& &&
#+end_src
得到:
#+begin_src cpp
  int&&
  double&&
  std::sting&
#+end_src
** ~std::forward<Args>(args)...~
这是一次 *包展开 (pack expansion)*:

假设:
#+begin_src cpp
  Args = <A0, A1, A2>;
  args = <arg0, arg1, arg2>;
#+end_src
那么 ~std::forward<Args>(args)...~会展开为:
#+begin_src cpp
  std::forward<A0>(arg0);
  std::forward<A1>(A1);
  std::forward<A2>(A2);
#+end_src
这里最关键的一点是: ~Args~ 和 ~args~ 在同一个模式里同步展开，即按照位置一一配对。
* 参数包不是容器
这是理解参数包时最重要的边界之一。

参数包不是 ~vector~, ~array~, ~tuple~ 这一类的容器。依然不是运行期对象，不存在 ~args[0]~, ~args.begin()~, ~args.size()~ 之类的操作。参数包只是编译器在模板实例化期间掌握的一组:

- 类型
- 值
- 模板
- 函数参数


例如:
#+begin_src cpp
  template <typename... Ts>
  struct TypeList {};
#+end_src
实例化为:
#+begin_src cpp
  TypeList<int, double, std::string> types;
#+end_src
这里的 ~Ts~ 是由三个类型组成的参数包，但是运行时不存在一个叫做 ~Ts~ 的集合对象。
* 参数包的种类
** 类型参数包
最常见:
#+begin_src cpp
  template <typename... Ts>
  struct TypeList {};
#+end_src
~Ts~ 表示零个或多个类型。例如:
#+begin_src cpp
  TypeList<> empty;
  TypeList<int> one;
  TypeList<int, double, std::string> many;
#+end_src
** 非类型模板参数包
参数包也可以保存编译期值:
#+begin_src cpp
  template <std::size_t... Indices>
  struct IndexList {};
#+end_src
例如:
#+begin_src cpp
  IndexList<0, 2, 4, 6, 8> indices;
#+end_src
这里的 ~Indices~ 包含 ~0, 2, 4, 6, 8~. 现代C++还可以写成:
#+begin_src cpp
  template <auto... Values>
  struct ValueList {};
#+end_src
** 模板模板参数包
参数包中的元素也可以是模板:
#+begin_src cpp
  template <
      template <typename...> typename... Containers
  >
  struct ContainerRegistry {};
#+end_src
** 函数参数包
#+begin_src cpp
  template <typename ...Args>
  void f(Args... args);
#+end_src
这里的 ~Args~ 是模板参数包， ~args~ 是函数参数包。两者通常长度一致，并且位置一一对应。
* ~...~ 在不同位置的语义
** 声明模板参数包
#+begin_src cpp
  template <typename... Args>
#+end_src
** 声明函数参数包
#+begin_src cpp
  Args&&... args
#+end_src
意思是:
#+begin_quote
根据 ~Args~ 中的每个类型，声明对应的函数参数。
#+end_quote
** 展开模板参数包
#+begin_src cpp
  std::tuple<Args...>
#+end_src
假设: ~Args = <int, double, std::string>~, 展开结果是:
#+begin_src cpp
  std::tuple<int, double, std::string>
#+end_src
** 展开函数参数包
#+begin_src cpp
  target(args...)
#+end_src
** 展开一个完整模式
#+begin_src cpp
  std::forward<Args>(args)...
#+end_src
这里展开的模式是:
#+begin_src cpp
  std::forward<Args>(args)
#+end_src
每次展开同时取出一个 ~Args~ 和一个 ~args~
* 获取参数包的长度
使用 ~sizeof... (pack)~. 它会返回编译期常量，并不会求值参数包中的表达式。
* 包展开不是运行期循环
考虑:
#+begin_src cpp
  template <typename... Args>
  void call_target(Args&&... args)
  {
      target(std::forward<Args>(args)...);
  }
#+end_src
调用 ~call_target(1, 2.0, name)~ ，编译期会实例化出一个具体函数，其效果近似于:
#+begin_src cpp
  void call_target(int&& arg0, double&& arg1, std::string& arg2) {
    target(std::forward<int>(arg0), std::forward<double>(arg1), std::forward<std::string&>arg2);
  }
#+end_src
因此参数包展开并不是理解中的循环结构:
#+begin_src cpp
  for (...) {
    ...
  }
#+end_src
而是在编译期就生成重复的语法结果。
* 如何逐个处理参数包
参数包本身并不能遍历，但可以进行处理。常见方法有两种:
** 递归展开 C++11 风格

#+begin_src cpp
  void print() {
    std::cout << '\n';
  }

  template <typename First, typename... Rest>
  void print(First&& first, Rest&&... rest) {
    std::cout << std::forward<First>(first);
    if constexpr (sizeof...(Rest) != 0) {
      std::cout << ", ";;
    }
    print(std::forward<Rest>(rest)...);
  }
#+end_src
剩余的参数包会被自动匹配成 ~First&& first~ 和 ~Rest&&... rest~ 的形式。
** 折叠表达式: C++17起
#+begin_src cpp
  template <typename... Args>
  void print(Args&&... args) {
    ((std::cout << std::forward<Args>(args) << ' '), ...);
  }
#+end_src
核心是:
#+begin_src cpp
  (expression_using_args, ...);
#+end_src
假设有三个参数，概念上会展开为:
#+begin_src cpp
  (std::cout << arg0 << ' '),
  (std::cout << arg1 << ' '),
  (std::cout << arg2 << ' ');
#+end_src
使用逗号运算符将多个表达式连接起来。

再比如求和:
#+begin_src cpp
  #include <concepts>

  template <std::integral... Ts>
  auto sum(Ts... values)
  {
      return (0 + ... + values);
  }
#+end_src
调用 ~sum(1, 2, 3, 4);~ 展开结果近似于:
#+begin_src cpp
  (((0 + 1) + 2) + 3) + 4
#+end_src
* 常见误区
** 误区一：参数包是一个 tuple
不是。 ~Args~ 只是编译期参数序列。只有显式写出 ~std::tuple<Args...>~ 才能构造出一个 tuple 类型。
** 误区二：可以直接访问第一个参数
传统参数包通常不能直接写:
#+begin_src cpp
  args[0];
  Args[0];
#+end_src
通常需要：
- 递归分解
- 转换成 ~std::tuple~
- 使用 ~std::index_sequence~
- 使用折叠表达式
** 误区三: ~Args&&...~ 永远是右值引用
形如:
#+begin_src cpp
  template <typename... Args>
  void f(Args... args);
#+end_src
发生模板推导时，每个 ~Args&&~ 都是转发引用。但如果使用 ~const~ 修饰，则不是转发引用。
** 误区四: 函数中的 ~args~ 保持原来的值类别
不保持。所有带名字的变量表达式都是左值，包括声明类型为右值引用的函数参数。

因此泛型初始化需要 ~std::forward<Args>(args)...~ 确保保留每个参数的值类别和类型。
* 小结
因此，可以将参数包的机制概括为：
#+begin_quote
参数包负责表示一列编译期元素，包展开负责把某个语法模式应用到这一列的每个元素上。
#+end_quote

核心就是:
#+begin_example
  声明一个包
      ↓
  模板推导填充这个包
      ↓
  用 pattern... 展开
      ↓
  生成一个具体的模板实例
#+end_example
