:PROPERTIES:
:END:
#+title: Preface
#+date:       [2026-06-11 Thu 00:21]
#+identifier: 20260611T002128
* 为什么阅读这本书
现代 C++ 可以视为以下面三部分组成:
- 低级语言，其中大部分继承自 C
- 更高级的语言特性，允许我们自定义类型，并组织大规模程序和系统
- 标准库，它使用这些高级特性来提供有用的数据结构和算法


市面上大多数文本都按照 C++ 的演变顺序呈现。它们首先教授 C++ 的 C 子集，并在书的结尾将 C++ 的更抽象的特性作为高级主题呈现。这种方法有两个问题: 读者可能在低级编程的固有细节中陷入困境，并在沮丧中放弃。而那些坚持学习坏习惯的人，他们以后必须改掉。

本书采用相反的方法：从一开始，我们就让程序员忽略低级编程中固有的细节的功能。例如，我们引入使用库字符串和向量类型以及内置的算术和数组类型。使用这些库类型的程序更容易编写，更容易理解，并且更不容易出错。

库经常被当作一个“高级”的主题进行教学。有很多书籍不使用库，而是使用基于指向字符数组的指针和动态内存管理的基础的低级编程技术。让使用这些低级技术的程序正确运行比使用库编写相应的 C++ 代码困难得多。

在整本书中，我们强调良好的风格: 我们希望帮助到读者立即养成良好的习惯，同时避免在未来获得更复杂的知识时需要改掉坏习惯。我们强调了特别棘手的事情，并警告了常见的误解和陷阱。

我们还解释规则背后的原理——解释为什么，而不仅仅是什么。我们相信通过理解事物为什么会这样工作，读者可以更快地巩固他们对于语言的掌握。

本书假设读者对编程有足够的了解，可以至少使用一种现代快结构编程语言编写、编译和运行程序。特别的，本书假设读者能够使用变量，书写和调用函数，并使用编译器。
* 本书的结构
我们首先在第一部分和第二部分中一起涵盖了语言和库。这些部分涵盖了足够的材料，能够让读者编写重要的程序。大多数C++程序员基本上需要知道本书这一部分所涵盖的一切。

除了教授 C++ 的基础知识外，第一部分和第二部分的材料还有一个重要作用: 通过使用库定义的抽象设施 (abstract facilities) ，读者将更加自如地使用高级编程技术。库设施 (llibrary facilities) 本身就是抽象数据类型，通常使用 C++ 编写，可以使用任何 C++ 程序员可用的相同类构建功能来定义库。我们在教授 C++ 方面的经验是：通过首先使用精心设计的抽象类型，读者更容易发现如何构建自己的类型。

只有在彻底了解使用库并编写库允许的抽象程序之后，我们才能转向那些 C++ 特性，这些特性将使读者能够编写在自己的抽象。第三部分和第四部分侧重于以类的形式书写抽象。第三部分涵盖基础内容，第四部分则包括更特殊的功能。

在第三部分中，我们将讨论拷贝控制 (copy control) 的相关问题，以及其他使类的使用体验与内置类型同样便捷的技术。类是面向对象和泛型编程的基础，这些内容我们同样在第三部分中进行简介。本书以第四部分收尾，该部分介绍了在构建大型复杂系统时最为实用的特性。此外，我们在附录A中对库中的算法进行了总结。
