:PROPERTIES:
:ID:       6554c5c9-2d52-440d-b024-dc6ba0039d32
:END:
#+title: Getting Started

本章介绍 C++中的大多数基础内容: 类型，变量，表达式，语句和函数。在此过程中，我们将简要说明如何编译和运行程序。

在阅读本章节以及做完对应的练习之后，你应该能够编写、编译和运行简单的程序。后续章节将假定你能够使用本章中介绍的特性，同时会更加细节地介绍这些特性。

学习一门新编程语言的方式是编写程序。在本章中，我们将编写一个程序，为一家书店解决一个简单的问题。我们的书店保存着一个交易文件，每条都记录着包含一本书的一本或多本销售情况。每条记录包含三个数据元素:
#+begin_example
0-201-70353-X 4 24.99
#+end_example
第一个元素是 ISBN(Internal Standard Book Nunber, 一种唯一的书本标识符)；第二个元素是销量，最后一个是每本书的售价。书店老板会时不时地查看这个文件，并针对每本书计算其销量、总收入以及平均售价。

为了完成这个程序，我们需要涵盖一些基础的 C++ 特性。此外，我们还需要知道如何编译和执行程序。

尽管我们此前并没有设计过程序，但不难看出它需要:
- 定义变量
- 进行输入和输出
- 使用数据结构来存储数据
- 检测两条记录的 ISBN 是否相等
- 包含一个循环，用于处理交易文件中的每一条记录。

  我们将首先回顾如何使用 C++ 解决这些子问题，然后编写我们的书店程序。
* Writing a Simple C++ Program
每一个 C++ 程序都包含一个或多个函数 (functions)，其中必须有一个名为 ~main~ 。操作系统通过调用 ~main~ 来运行 C++ 程序。这里有一个简单版本的 ~main~ 实现，仅仅返回一个值给操作系统:
#+begin_src c++
  int main ()
  {
    return 0;
  }
#+end_src
一个函数定义具有四个元素: 一个返回类型 (return type), 一个函数名称 (function name) ，一个由圆括号包围的参数列表 (parameter list), 以及一个函数体 (function body)。尽管 ~main~ 函数有些特殊，但我们定义 ~main~ 的方式与其他函数别无二致。

上面的例子中， ~main~ 具有空的参数列表。后续的章节将讨论能够在 ~main~ 中定义的其他参数。

~main~ 函数需要有一个 ~int~ 类型的返回值，代表整数。这个 ~int~ 类型是内置类型，这意味着它是该语言定义的类型之一。

函数定义的最后一部分，函数体，是一组语句块。

这个语句块中唯一的语句就是 ~return~ ，它能够终结一个函数。正如我们所示的， ~return~ 还能够发送一个值给函数的调用者。当一个 ~return~ 语句包含一个值的时候，这个返回值必须和函数的返回类型匹配。在这种情况下， ~main~ 函数的返回类型是 ~int~ 并且返回值是 0 ，是一个 ~int~ 。

在大多系统中， ~main~ 的返回值是一个状态标识符。返回值 ~0~ 标志着成功，非零的返回值的意义由系统定义——通常表示某种类型的错误。


#+begin_concept
Types 类型是编程中最重要的基础概念。一个类型同时定义了数据元素的内容和这个数据可能拥有的操作。\\
我们的程序所操作的数据存储在变量中，每个变变量都拥有一个类型。当变量 V 的类型是 T 时，我们通常说 V 的类型是 T,或者等同地说 V 是一个 T
#+end_concept
** Compiling and Executing Our Program
*** Program Source File Naming Convention
大多数编译器期望源代码存储在一个或多个文件中。程序文件通常会被称为源文件 (source files) 。在大多数系统中，源文件的名称以一个后缀结尾，该后缀由一个 ~.~ 后跟一个或多个字符组成，该后缀告诉系统该文件是一个 ~C++~ 程序。不同编译器采用不同的后缀约定；最常见的包括 ~.cc~ , ~.cxx~ , ~.cpp~ , ~.cp~ 和 ~.c~ 。
*** Running Compiler from Command Line
假设我们的程序位于 ~prog1.cc~ 文件中，那么可以通过下面的命令编译:
#+begin_src bash
  cc prog1.cc
#+end_src
~CC~ 表示编译器。编译器会生成一个可执行文件，在 Windows 系统上，该可执行文件命名为 ~prog1.exr~ 。 UNIX 编译器通常将可执行文件保存在名为 ~a.out~ 的文件中。

在 UNIX 上需要通过 ~./a.out~ 命令来在当前目录运行程序。 ~main~ 返回的值需要根据系统不同进行访问，在 UNIX 系统上，执行命令之后，需要通过:
#+begin_src bash
  echo $?
#+end_src
来进行查看。
** A First Look at Input/Output
C++ 语言本身并未定义任何用于输入或输出的语句。相反，C++ 包含一个功能强大的标准库，该库提供了输入输出（和其他许多功能）。对于许多的用途而言，包括本书中的示例，只需要掌握 IO 库中的几个基本概念和操作即可。

本书中的大部分例子都使用了 ~iostream~ 库。 ~iostream~ 库的核心是两个名为 ~istream~ 和 ~ostream~ 的类型，它们分别代表输入流和输出流。流 (stream) 是一系列从 I/O 设备读取或写入的字符。“流”这一术语旨在说明，这些字符是随着时间顺序生成或消耗的。
*** Standard Input and Output Objects
这个库定义了四种 IO 对象。为了处理输入，我们使用 ~istream~ 类型中的一个对象，名为 ~cin~ (发音为 ~see-in~) 。这个对象也被称为标准输入。对于输出，我们使用一个名为 ~cout~ （发音为 ~see-out~ ）的 ~ostream~ 对象。该对象也被称为标准输出。该库还定义了其他两种 ~ostream~ 类型对象，分别称为 ~cerr~ 和 ~clog~ 。我们通常使用被称为标准错误的 ~cerr~ 来输出错误和警告信息，而使用 ~clog~ 来输出有关程序执行的一般信息。

通常情况下，系统会将这些对象分别与程序所运行的窗口相关联。因此，当我们从 ~cin~ 读取数据时，数据是从程序运行的窗口中读取的，而当我们向 ~cout~, ~cerr~, ~clog~ 写入数据时，输出也会写入同一个窗口。
*** A Program That Uses the IO Library
在我们的书店问题中，我们将把一些记录汇总到一个单独的地方。作为一个简单的相关联的问题，让我们看一下我们如何将两个数相加。使用 IO 库，我们可以扩展 ~main~ 程序，以提示用户给我们两个数并打印它们的和:
#+begin_src cpp
  #include <iostream>
  int main ()
  {
    std::cout << "Enter two numbers: " << std::endl;
    int v1 = 0, v2 = 0;
    std::cin >> v1 >> v2;
    std::cout << "The Sum of " << v1 << " and " << v2 << " is " << v1 + v2 << std::endl;
    
    return 0;
  }
#+end_src
第一行 ~#include <iostream>~ 告诉编译器我们想要使用 ~iostream~ 这个库。在 ~<>~ 内部的名称指向一个头文件 (header) 。任何使用库功能的程序都必须包含对应的头文件。 一般而言，我们将程序中所有的 ~#include~ 指令都放在源文件的开头。通通通通通通通常， ~#include~ 指令必须放在任何函数之外。
*** Writing to a Steam
函数体的第一条语句执行了一个表达式 ([[id:2555287b-9c63-4f18-b69a-d64288bc0aa9][expression]]) 。在 C++ 中，表达式会产生一个结果，由一个或多个操作数 (operands) 和通常一个操作符 (operator) 组成。该语句中的表达式使用输出操作符(~<<~ 操作符) 将一条信息打印到标准输出:
#+begin_src cpp
  std::out << "Enter two numbers" << std::endl;
#+end_src
~<<~ 的操作符接受两个操作数: 左侧的操作数必须是一个 ~ostream~ 对象，右侧的操作数是要被打印的值。该操作符将值写入到指定的 ~ostream~ 。输出操作符的结果是其左侧的操作数，也即是说，结果就是我们写入该值的 ~ostream~ 。

我们的输出语句使用了两次 ~<<~ 操作符。由于该操作符返回其左侧的操作数，因此第一个运算符的结果便成为第二个运算符的左侧的操作数。因此，我们可以将输出请求串联起来，表达式等同于:
#+begin_src cpp
  (std::cout << "Please enter two numbers: ") << std::endl;
#+end_src
这条链中每一个操作符都使用相同的对象作为其左操作数，在本例中即位 ~std::out~ 。或者，我们也可以用两条语句实现相同的输出:
#+begin_src cpp
  std::cout << "Please enter two numbers: ";
  std::cout << endl;
#+end_src
第二个运算符输出 ~endl~ ，这是一个被称为 ~manipulator~ 的特殊值。写入 ~endl~ 的作用是结束当前行并刷新与该设备关联的缓冲区 (flushing the buffer) 。刷新缓冲区可确保程序到现在为止生成的所有输出都确实被写入输出流，而不是滞留在内存中等待写入。

#+begin_warning
程序员经常在调试的时候添加打印语句。此类语句应使用刷新输出流。否则，如果程序崩溃，输出内容可能残留在缓冲区中，从而导致对程序崩溃为止的推断出现错误。
#+end_warning
*** Using Names from the Standard Library
对于我们上面用到的 ~std::cout~ 和 ~std::endl~ ，其中的 ~std::~ 前缀，标志着 ~cout~ 、 ~endl~ 这些名字是在一个名为 *std* 的命名空间 (namespace) 中被定义的。命名空间允许我们去避免在定义的名称与库内部对这些名称的使用之间发生意外冲突。标准库中定义的所有名字均位于 std namepsace 中。

库使用命名空间的一个副作用是: 当我们使用库中的某个名字时，必须明确指出我们要使用的是来自 ~std~ 命名空间的该名字。在 ~std::cout~ 中，我们使用 ~::~ (作用域运算符) 操作符来表明我们希望使用定义在 ~std~ 命名空间中的 ~cout~ 名字。
*** Reading from a Stream
在用户要求输入之后，我们下一步希望读取这个输入。从定义两个变量:名为 ~v1~ 和 ~v2~ 开始，并用这两个变量保存用户输入:
#+begin_src cpp
  int v1 = 0, v2 = 0;
#+end_src
我们将这些变量定义为 ~int~ 类型，这是一种表示整数的内置类型。我们还会将其初始化为 ~0~ 。初始化变量时，会在创建变量的同时为其赋予指定的值。

下一个语句是:
#+begin_src cpp
  std::cin >> v1 >> v2;
#+end_src
从输入读取。输入操作符 ( ~>>~ ) 的行为与输出操作符类似。它将一个 ~istream~ 对象作为左操作数，并将一个对象作为右操作数。它从给定的 ~istream~ 中读取数据，并将读取到的数据存储在给定的对象中。与输出操作符一样，输入操作符返回其左操作数作为结果。因此，该表达式等同于:
#+begin_src cpp
  (std::cin >> v1) >> v2;
#+end_src
由于该操作符返回其左操作数，我们可以将一系列输入请求组合为一个语句。我们的输入操作从 ~std::cin~ 读取两个值，将第一个值存储在 ~v1~ 中，将第二个值存储在 ~v2~ 中，换句话说，我们的输入操作执行顺序如下:
#+begin_src cpp
  std::cin >> v1;
  std::cin >> v2;
#+end_src
*** Completing the Program
接下来只需要打印结果:
#+begin_src cpp
  std::cout << "The sum of " << v1 << " and " << v2 << " is " << v1 + v2 << std::endl;
#+end_src
虽然这条语句比那条向用户请求输入的语句更长，但是其原理是相似的。它将每个操作数都输出到标准输出。本例中有趣之处在于，这些操作数并非全都属于同一类型的值。有些操作数是字面量，有些则是整数值。该库定义了输入和输出运算符的多种版本，用于处理这些不同类型的操作数。

-----
** A Word about Comments
注释 (comments) 帮助人们阅读我们的程序。它们通常用于概括算法、说明变量的用途、或者阐明原本晦涩的代码段。编译器会忽略注释，因此它们不会对程序的性能或者行为产生任何影响。

程序员往往会相信注释，即使系统文档的其他部分已经过时。当修改代码的同时请务必修改注释。
*** C++ 中注释的类型
分为两种: 单行注释和成对注释。一个单行注释以 ~//~ 开头，并且在新一行结束。所有在 ~//~ 后面的内容都被编译器视为注释。

成对注释通过 ~/* */~ 记录。这种风格继承自C. 被 ~/* */~ 包裹的内容全部会被视为注释。

成对注释可以放置在允许使用制表符、空格或换行符的任何位置。它可以跨越程序中的多行，但并非必须如此。当成对注释跨越多行时，建议通过视觉方式表明这些行属于多行注释。我们的风格是在注释中的每行开头添加一个 ~*~ ，以此表明。

下面是一个示例，有关两个注释类型:
#+begin_src cpp
  #include <iostream>
  /*
   ,* Simple main function:
   ,* Read two numbers and write their sum
   ,*/
  int main(){
    // prompt user to enter two numbers
    std::cout << "Enter two numbers: " << std::endl;
    int v1 = 0, v2 = 0; // varibles to hold the input we read
    std::cin >> v1 >> v2;
    std::cout << "The sum of " << v1 << " and " << v2 << " is " << v1 + v2 << std::endl;
    return 0
  }
#+end_src

-----

** Flow of Control
语句通常按顺序执行：块中的第一个语句最先执行，其次是第二个，以此类推。当然很少有程序能仅仅依靠顺序执行就解决问题。为解决这个问题，编程语言提供了各种控制流语句，从而支撑更加复杂的执行路径。


*** The ~while~ Statement
~while~ 语句会在给定条件为真时，反复执行同一段代码。比如:
#+begin_src cpp
  #include <iostream.
  int main () {
    int sum = 0 val = 1;
    while (val <= 10) {
      sum += val;
      ++val;
    }
    std::cout << "Sum of 1 to 10 inclusive is " << sum << std::endl;
    return 0;
  }
#+end_src
编译然后运行该程序，就会得到输出:
#+begin_quote
Sum of 1 to 10 inclusive is 55
#+end_quote
