:PROPERTIES:
:ID:       1b794026-5684-40c3-a605-285c5829b2c4
:END:
#+title: OCaml 和 Shell 的模式匹配
* OCaml 模式匹配与 Shell ~case ... in ...~ 对比

我们已经接触过 Shell 的：

#+begin_src bash
  case "$value" in
      pattern1)
  	commands
  	;;
      pattern2)
  	commands
  	;;
  esac
#+end_src

现在正在学习 OCaml 的:

#+begin_src ocaml
  match value with
  | pattern1 -> expression1
  | pattern2 -> expression2
#+end_src

会感觉到两者很相似。它们都采用一种“按顺序尝试候选模式，并执行第一个成功分支”的控制结构。

然而，OCaml 与 Shell 对 “模式” 的理解有很大区别。 Shell 的 ~case~ 主要处理文本分类； OCaml  的模式匹配可以直接观察数据结构、提取内部字段，并在编译阶段接受类型检查与完整性检查。

理解这一差异，是进入 OCaml 代数数据类型、递归数据结构和函数式编程思想的重要一步。

-----
* 最接近的例子

假设我们需要根据命令行参数执行不同操作。

Shell 可以这样写：
#+begin_src bash
  case "$1" in
      start)
  	echo "starting"
  	;;
      stop)
  	echo "stopping"
  	;;
      restart)
  	echo "restarting"
  	;;
       *)
  	echo "unknown command"
  	;;
  esac    
#+end_src

OCaml 中可以写成：

#+begin_src ocaml
  let describe_command command =
    match command with
      | "start" -> "starting"
      | "stop" -> "stopping"
      | "restart" -> "restarting"
      | _ -> "unknown command"
#+end_src

两套代码都遵循同一个基本流程：

1. 取得一个特定的值
2. 按照从上到下的顺序检查分支
3. 执行对应代码
4. 后续分支不再继续尝试

Bash 官方手册明确说明， ~case~ 中第一个匹配成功的模式决定将要执行的命令列表；通常 ~*~ 放在最后，作为匹配任意字符串的默认分支。 OCaml 的 ~match~ 也按照分支顺序进行选择。

可以先建立一组对应关系：

| Shell           | OCaml              | 作用                 |
|-----------------+--------------------+----------------------|
| ~case value in~ | ~match value with~ | 指定待匹配的值       |
| ~start)~        | ~\vert "start" ->~ | 声明一个候选分支     |
| ~*~             | ~_~                | 兜底模式             |
| ~command-list~  | ~expression~       | 匹配成功后执行的内容 |
| ~esac~          | 无需结束关键字     | 结束整个结构         |

不过这张表只描述了最基础的相似性。接下来需要逐步拆开两者的差异。

----
* Shell 的 ~case~: 面向字符串的 glob 模式分类
** Shell 匹配的对象一般是一段文本
在 POSIX  Shell 中， ~case~ 的基本格式是：

#+begin_src bash
  case word in
      pattern1)
  	compound-list
  	;;
      pattern2)
  	compound-list
  	;;
      ;;
esac
#+end_src
Shell 会首先对 ~word~ 进行必要的展开，再将结果依次与各个模式比较。POSIX 标准将其定义为 Shell 命令语句中的条件结构。

例如:

#+begin_src bash
    filename="report.pdf"

    case "$filename" in
        ,*.pdf)
    	echo "PDF document"
    	;;
        ,*.txt)
    	echo "text docuemnt"
    	;;
        ,*)
    	echo "other file"
    	;;
    esac      
#+end_src

其中的 ~*.pdf~ 是 shell pattern ，也称为 global pattern 它表达的是:

#+begin_quote
任意字符序列，后面跟着字面量 ~.pdf~ 。
#+end_quote

它与正则表达式有相似用途，但语法体系不同。Bash 官方文档列出的基本特殊字符包括：

| glob 模式 | 含义                               |
|-----------+------------------------------------|
| ~*~       | 匹配任意长度的字符串，包括空字符串 |
| ~?~       | 匹配任意单个字符                   |
| ~[abc]~   | 匹配集合中的任意一个字符           |
| ~[a-z]~   | 匹配指定范围内的单个字符           |
| ~[!abc]~  | 匹配集合之外的单个字符             |

例如:

#+begin_src bash
  case "$answer" in
      y | Y | yes | YES)
  	echo "accepted"
  	;;
      n | N | no |NO)
  	echo "rejected"
  	;;
      ,*)
  	echo "invalid input"
  	;;
  esac
#+end_src

其中 ~y | Y | yes | YES~ 表示若干个候选模式共享同一段命令。
** Shell 的模式匹配常用于分类，不会自动提取内部部分
考虑:

#+begin_src bash
  case "$filename" in
      ,*.pdf)
  	echo "PDF docuemnt"
  	;;
  esac
#+end_src
Shell 能判断 ~"report.pdf"~ 是否匹配 ~*.pdf~ ，但不会自动将 ~"report"~ 提取为一个变量。

假如需要提取扩展名前面的文本，通常需要使用参数展开、 ~basename~ 、 ~cut~ 、 ~sed~ 或其他工具。例如：
#+begin_src bash
  filename="report.pdf"
  stem="${filename%.pdf}"
  echo "$stem"
#+end_src

结果是 ~report~ 。

~case~ 本身只负责判断分支；提取操作需要额外书写。
** Shell 中每个分支是一组命令
Shell 的分支内容通常是一串具有副作用的命令：

#+begin_src bash
  case "$action" in
      build)
  	mkdir -p dist
  	cp app dist/
  	echo "build completed"
  	;;
  esac
#+end_src

这些命令可能创建目录、复制文件、启动进程或打印文本。 ~case~ 在 Shell 中首先是一种控制流结构。

-----
* OCaml 的 ~match~: 面向数据形状的结构化匹配
OCaml 的模式匹配同样可以比较字符串:

#+begin_src ocaml
  let describe_extensions extension =
    match extension with
    | "pdf" -> "PDF docuemnt"
    | "txt" -> "text document"
    | _ -> "unkown docuemnt"
#+end_src
但这只是最简单的用途。 OCaml 模式可以深入数据结构内部，并将其中的组成部分绑定到局部变量。

OCaml 官方文档对模式匹配用于处理原子类型、元组、列表、记录以及用户自定义的 variant 类型。对于列表等数据结构，检查结构和拆解内容通常直接通过模式匹配完成。

-----
** OCaml 的变量模式可以完成绑定
看一个最简单的例子：

#+begin_src ocaml
  let describe_number n =
    match n with
    | 0 -> "zero"
    | x -> "non-zero number: " ^ string_of_int x
#+end_src

这里的 ~| 0 -> "zero"~ 表示只匹配整数 ~0~ 。而 ~| x-> ...~ 表示匹配任意整数，并将实际值绑定到变量 ~x~ 。

这里必须注意， ~| x -> ...~ 中的 ~x~ 不是一个提前定义好的变量，也不是“检查输入是否等于变量 ~x~ 的值”。它是一个新的局部绑定，这里和函数参数十分相似:

#+begin_src ocaml
  let identity x = x
#+end_src

函数接收一个值，并将其命名为 ~x~ 。模式匹配分支中的变量也会接收一个值，并在右侧表达式中提供一个名字。
** ~_~ 表示忽略值
如果分支需要匹配任意值，却不关心这个值具体是什么，可以使用通配符模式： ~_~ 。

例如:

#+begin_src ocaml
  let is_zero n =
    match n with
    | 0 -> true
    | _ -> false
#+end_src
这里 ~_~ 和 Shell 中常见的 ~*~ 在兜底分支上有相似作用，用 Shell 可以这样写:

#+begin_src bash
  case "$n" in
      0)
  	echo "true"
  	;;
      ,*)
  	echo "false"
  	;;
  esac
#+end_src

不过两者含义并不完全相同:

| 写法         | 含义                             |
|--------------+----------------------------------|
| Shell 的 ~*~ | 匹配任意字符串                   |
| OCaml 的 ~_~ | 匹配当前类型下的任意值，并忽略它 |
** OCaml 可以拆解元组
假设我们有一个二维坐标:

#+begin_src ocaml
  let point = (3, 5)
#+end_src
可以直接匹配其内部结构：
#+begin_src ocaml
  let describe_point point =
    match point with
    | (0, 0) -> "origin"
    | (0, y) -> "on the y-axis at " ^ string_of_int y
    | (x, 0) -> "on the x-axis at " ^ string_of_int x
    | (x, y) -> "point (" ^string_of_int x ^ ", " ^ string_of_int y ^ ")"
#+end_src
如果调用 ~describe_point(0, 7)~ ， OCaml 会尝试匹配 ~(0, y)~ ，第一个位置必须要求 ~0~ ，第二个位置可以是任意整数，并绑定到变量 ~y~ 。

所以结果是: ~on the y-axis at 7~ 。

在 Shell 中，如果使用字符串表示坐标: ~point="0,7"~ ， ~case~ 可以粗略判断:

#+begin_src bash
  case "$point" in
      0,*)
  	echo "possibly on the y-axis"
  	;;
  esac
#+end_src

但是 ~case~ 不会知道逗号前后分别是两个整数，也不会自动建立 ~y=7~ 的绑定。 Shell 只能看到一串字符。

而 OCaml 则知道 ~(0, 7)~ 的类型为:

#+begin_src ocaml
  int * int
#+end_src

并按照元组结构进行拆解。

-----
* 最重要的差异：OCaml 模式描述数据结构
** 列表模式
OCaml 的列表可以递归地定义为：
#+begin_quote
空列表 \\
或 \\
一个头部元素，加上剩余列表
#+end_quote
因此，列表常用两种模式：
- ~[]~
- ~head::tail~


例如:
#+begin_src ocaml
  let describe_list xs =
    match xs with
      | [] -> "empty list"
      | head :: tail -> "first element is " ^ string_of_int head
#+end_src

调用 ~describe_list [10; 20; 30]~ ，匹配过程可以理解为：

#+begin_src ocaml
  [10; 20; 30]
  =
  10 :: [20; 30]
#+end_src
于是， ~head = 10~ ， ~tail = [20; 30]~ 。

这里，已经明显超出了 Shell ~case~ 的能力范围。 OCaml 在一次匹配中同时完成了三件事情：
1. 判断列表是否为空
2. 识别非空列表的结构
3. 提取第一个元素和剩余列表


进一步，我们可以递归处理列表：

#+begin_src ocaml
  let rec sum xs =
  match xs with
  | [] -> 0
  | head::tail -> head + sum tail
#+end_src
模式匹配在这里直接对应列表的递归定义。它不只是分支选择语法，也是一种描述数据结构的语言。

-----
** 嵌套模式
模式可以层层嵌套：
#+begin_src ocaml
  let describe_points points =
    match points with
    | [] -> "no points"
    | (0, 0) :: tail -> "the first point is origin"
    | (x, y) :: tail -> "the first point is (" ^
                          string_of_int x ^ ", " ^
                            string_of_int y ^ ")"
#+end_src
假设输入: ~[(0, 0); (3, 4); (5, 8)]~ ，模式 ~(0, 0) :: tail~ 同时检查了两层结构：
- 最外层：它是一个非空列表吗？
- 内层：第一个元素是坐标原点吗？


匹配成功后: ~tail = [(3, 4); (5, 8)]~ 。
Shell 的 glob 模式也有一定的结构描述能力，比如 ~src/*.ml~ 可以表示 ~src/~ 开头， ~ml~ 结尾的字符串。但 OCaml 模式描述的是类型化结构的数据构造方式。列表、元组、记录和 variant 都保留自身结构，不需要先转化为文本。

-----
* variant: OCaml 模式匹配发挥力量的地方
OCaml 允许定义 variant 类型，也称变体类型。它可以表达“一个值可能具有若干种形式”。

例如:

#+begin_src ocaml
  type shape =
    | Circle of float
    | Rectangle of float * float
    | Point
#+end_src

这个类型声明表明，一个 shape 值可能是：
- Circle ，并携带一个 float
- Rectangle ，并携带两个 float
- Point ，不携带任何额外数据


可以通过模式匹配计算面积：

#+begin_src ocaml
  let area shape =
    match shape with
    | Circle radius ->
       Float.pi *. radius *. radius
    | Rectangle (width, height) ->
       width *. height
    | Point ->
       0.0
#+end_src

可以这样执行: ~area (Circle 2.0)~ ，这会匹配到 ~Circle radius~ ，并绑定到 ~radius = 2.0~ 。

再看 ~area (Rectangle (3.0, 4.0))~ 匹配到 ~Rectangle (width, height)~ ，并绑定 ~width = 3.0, height = 4.0~ ，最终会得到 ~12.0~ 。
** 与 Shell 的区别
假设 Shell 中使用字符串编码图形：

#+begin_src bash
  shape="circle:2.0"
#+end_src

可以写:

#+begin_src bash
  case "$shape" in
      circle:*)
  	echo "circle"
  	;;
      rectangle:*)
  	echo "rectangle"
  	;;
  esac
#+end_src
这种写法能判断前缀，但是 Shell 并不知道 ~circle~ 后面必须跟一个浮点数， ~rectangle~ 后面必须跟两个浮点数。也无法仅靠 ~case~ 安全地将内部字段安全地转化为变量。

在 OCaml 中 ~Circle 2.0~ 不是一串经过约定的文本，而是一个由构造器 ~Circle~ 建立的值。编译器知道它属于 ~shape~ 类型，并知道它内部携带一个 ~float~ 。这种设计会让很多业务状态变得清晰。例如:

#+begin_src ocaml
  type request_result =
    | Success of string
    | Not_found
    | Permission_denied
    | Network_error of string
#+end_src

处理结果时:

#+begin_src ocaml
  let describe_result result =
    match result with
    | Success content -> "received: " ^ content
    | Not_found -> "resources does not exist"
    | Premission_denied -> "permission denied"
    | Network_error message -> "network error: " ^ message
#+end_src

每一种情况都具有明确的名字、明确的数据形状和明确的处理方式。

-----
* OCaml 的 ~match~ 是表达式
这是 OCaml 与 Shell 在编程范式上的另一项重要差异。
** Shell ~case~ 主要决定执行哪些命令
#+begin_src bash
  case "$mode" in
      debug)
  	echo "verbose logging enable"
  	;;
      release)
  	echo "optimized build enable"
  	;;
  esac
#+end_src

从阅读习惯上，会理解为：根据条件选择一组动作。
** OCaml ~match~ 会产生一个值
#+begin_src ocaml
  let message =
    match mode with
    | "debug" -> "verbose logging enabled"
    | "release" -> "optimized build enable"
    | _ -> "unknown mode"
#+end_src

整个的 ~match mode with ...~ 本身是一个表达式，它会计算出一个值，然后绑定给 meassage 。

下面的代码可以通过类型检查：
#+begin_src ocaml
  let result =
    match command with
    | "start" -> 1
    | "stop" -> 0
    | _ -> -1
#+end_src
每个分支都会返回 ~int~ ，所以 ~result : int~ 。下面的代码会出现类型错误:
#+begin_src ocaml
  let result =
    match command with
    | "start" -> 1
    | "stop" -> "stopped"
    | _ -> 0
#+end_src
原因在于 ~1~ 的类型是 ~int~ ，而 ~"stopped"~ 的类型是 ~string~ 。 OCaml 无法为整个 ~match~ 表达式推导出统一类型。可以将其类比为我们之前学过的 OCaml ~if~ ：

#+begin_src ocaml
  if condition then expr1 else expr2
#+end_src
~expr1~ 和 ~expr2~ 也拥有一致的类型，因为完整的 ~if~ 表达式会产生一个值。
